name: Check pull request source branch and post welcome comment
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branches
        run: |
          echo "Running check branches"
          if [[ ! ${{ github.head_ref }} =~ qa$|QA$ ]] && [ ${{ github.base_ref }} == "main" ]; then
            echo "Merge requests to main branch are only allowed from branches ending with 'qa' or 'QA'."
            exit 1
          fi

      - name: Post welcome comment
        run: |
          gh pr comment ${{ github.event.pull_request.html_url }} --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
